(def dim 40) 
(def scale 20)
(def size (* dim scale))
(def nants-sqrt 6) 
(def ladybugs-count 5)
(def aphis-count 50)
(def sugar-places 35) 
(def sugar-range 100)
(def pher-scale 20.0)
(def sugar-scale 30.0)
(def herb-scale 3)
(def evap-rate 0.8)
(def animation-sleep-ms 50) 
(def ant-sleep-ms (atom 200))
(def ladybug-sleep-ms (atom 1000))
(def aphis-sleep-ms (atom 400))
(def running true)
(def anthill-off (rand-int (- dim nants-sqrt)))
(def anthill-range 
	(range anthill-off (+ nants-sqrt anthill-off)))
(def bgcolor Color/Gray)